# Generated by Django 3.2.25 on 2026-05-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_area_number', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_limit', models.IntegerField()),
                ('parking_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('area_number', models.IntegerField()),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('parking_status', models.CharField(choices=[('Parked', 'Parked'), ('Leaved', 'Leaved')], default='Parked', max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('wrong_parking', models.BooleanField(default=False)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms1.category')),
            ],
        ),
    ]
