# Generated by Django 3.2.25 on 2026-05-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
